---
apiVersion: v1
kind: Service
metadata:
  name: ott-app
  labels:
    app: ott-app
spec:
  type: LoadBalancer  # Change this line to LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ott-app
